const $ = id => document.getElementById(id);
let token = '', project = 'default', state, activeTab = 'activity';
const rendered = new Map();
const titles = {activity:['Everything, as it happens.','Every task from every chat and every person: what it did, what it made, and where its files are.'],system:['Who uses it, and how much.','Tasks, model calls and tokens per person, plus the Claude Code and Codex hand-offs.'],tasks:['Make room for bigger ideas.','Give your agents a clear task. Keep the work, evidence, and decisions together.'],sources:['Good answers start with good sources.','A searchable library for this project. No extra GPU required.'],memory:['Keep the context that matters.','Durable preferences, decisions, and checkpoints for the next task.'],outputs:['Useful work, ready to use.','Reports, original drafts, and generated assets in one place.'],skills:['The right approach for the task.','Focused playbooks that your agents load only when needed.']};
function node(tag, text, cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(text=''){$('notice').textContent=text;$('notice').hidden=!text;}
function button(text, action, cls='quiet-light'){const e=node('button',text,cls);e.type='button';e.addEventListener('click',()=>Promise.resolve().then(action).catch(e=>notice(e.message)));return e;}
async function api(path, body){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:data.error||'Please check the fields and try again.');return data;}
function tab(name){activeTab=name;document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!=='tab-'+name);document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.tab===name));$('page-title').textContent=titles[name][0];$('page-description').textContent=titles[name][1];}
function empty(target,message){$(target).replaceChildren(node('div',message,'empty'));}
function list(target,items,render,message){const signature=JSON.stringify(items);if(rendered.get(target)===signature)return;rendered.set(target,signature);if(!items.length)return empty(target,message);$(target).replaceChildren(...items.map(render));}
function date(text){return text?new Date(text).toLocaleString():'';}
function card(title,text){const c=node('article',undefined,'card');c.append(node('h3',title));if(text)c.append(node('p',text));return c;}
async function refresh(){state=await api('state?project='+encodeURIComponent(project));$('unlock').hidden=true;$('workspace').hidden=false;$('connection').textContent=state.configured?'Gateway configured':'Gateway not configured';if(rendered.get('project-options')!==JSON.stringify(state.projects))$('project').replaceChildren(...state.projects.map(p=>{const o=node('option',p.name);o.value=p.id;return o;}));rendered.set('project-options',JSON.stringify(state.projects));$('project').value=project;$('project-name').textContent=state.projects.find(p=>p.id===project)?.name||'Workspace';$('running-count').textContent=state.jobs.filter(j=>['queued','running'].includes(j.status)).length;$('document-count').textContent=state.documents.length;$('post-count').textContent=state.posts;$('artifact-count').textContent=state.artifacts.length;
 const selected=$('skill').value;if(rendered.get('skill-options')!==JSON.stringify(state.skills))$('skill').replaceChildren(...state.skills.map(s=>{const o=node('option',s.name.replaceAll('-',' '));o.value=s.id;return o;}));rendered.set('skill-options',JSON.stringify(state.skills));$('skill').value=state.skills.some(s=>s.id===selected)?selected:'research-brief';skillDescription();$('frontier').disabled=!state.frontier_configured;
 $('attention-section').hidden=!state.attention.length;
 list('attention',state.attention,j=>{const c=card(j.reason,j.task.slice(0,160));c.append(button('Open task',()=>showJob(j.id)));return c;},'Nothing needs attention.');
 list('jobs',state.jobs,j=>{const c=card(j.task.slice(0,180));const meta=node('div',undefined,'meta');meta.append(node('span',j.status,'status '+j.status),node('span',j.skill.replaceAll('-',' ')+' · '+j.profile),node('span',date(j.created_at)));const actions=node('div',undefined,'card-actions');actions.append(button('View',()=>showJob(j.id)));if(['queued','running'].includes(j.status))actions.append(button('Cancel',async()=>{await api('jobs/'+j.id+'/cancel',{});await refresh();}));if(['failed','cancelled','interrupted'].includes(j.status))actions.append(button('Resume',async()=>{await api('jobs/'+j.id+'/resume',{});await refresh();}));meta.append(actions);c.append(meta);if(j.error)c.append(node('p',j.error));return c;},'Your next idea starts here. Create a task above to put the team to work.');
 list('documents',state.documents,d=>card(d.title,d.source+' · '+date(d.created_at)),'Add your first source above. Agents can cite and search it across future tasks.');
 list('memories',state.memories,m=>{const c=card(m.title,m.content);c.append(node('span',m.kind+' · '+date(m.updated_at),'muted'));c.append(button('Edit',()=>{$('memory-title').value=m.title;$('memory-content').value=m.content;$('memory-kind').value=m.kind;window.scrollTo({top:0,behavior:'smooth'});}));return c;},'No saved memory yet. Start with your audience, budget, or working preferences.');
 list('artifacts',state.artifacts,a=>{const c=card(a.name,date(a.created_at));c.append(button('Download file',()=>download(a)));return c;},'Finished reports and generated files will appear here.');
 list('drafts',state.drafts,d=>{const c=card(d.title,d.hook);const details=node('details');details.append(node('summary','Read draft'),node('p',d.script||''),node('p',d.caption||''),node('p','Source post IDs: '+d.source_post_ids));c.append(details,node('span',d.platform+' · '+d.status,'muted'));return c;},'Content skills save original scripts and captions here.');
 list('skills',state.skills,s=>{const c=card(s.name.replaceAll('-',' '),s.description);c.classList.add('skill-card');c.append(button('Use this skill ↗',()=>{tab('tasks');$('skill').value=s.id;skillDescription();$('task').focus();}));return c;},'No skills found.');
 await extras();
}
function duration(j){if(!j.started_at)return '';const end=j.finished_at?new Date(j.finished_at):new Date();const s=Math.round((end-new Date(j.started_at))/1000);return s<60?s+'s':Math.floor(s/60)+'m '+(s%60)+'s';}
async function extras(){
 const scope=$('activity-scope').value==='all'?'all':project;
 const act=await api('activity?project='+encodeURIComponent(scope));
 list('activity',act.jobs,j=>{const c=card((j.requested_by||'console')+' · '+j.project_name,j.task.slice(0,300));const meta=node('div',undefined,'meta');meta.append(node('span',j.status,'status '+j.status),node('span',j.skill.replaceAll('-',' ')),node('span',j.actions+' actions · '+j.files+' files'),node('span',duration(j)),node('span',date(j.created_at)));const actions=node('div',undefined,'card-actions');actions.append(button('Open',()=>showJob(j.id)));if(['queued','running'].includes(j.status))actions.append(button('Cancel',async()=>{await api('jobs/'+j.id+'/cancel',{});await refresh();}));meta.append(actions);c.append(meta);if(j.error)c.append(node('p',j.error));return c;},'No tasks yet. Anything sent from the chat site or started here shows up in this list.');
 const mscope=$('memory-scope').value==='all'?'all':project;
 const mem=await api('memories?project='+encodeURIComponent(mscope)+'&search='+encodeURIComponent($('memory-search').value));
 list('memories',mem.memories,m=>{const c=card(m.title,m.content);c.append(node('span',m.kind+' · '+m.project_name+' · '+date(m.updated_at),'muted'));const actions=node('div',undefined,'card-actions');actions.append(button('Edit',()=>{$('memory-title').value=m.title;$('memory-content').value=m.content;$('memory-kind').value=m.kind;window.scrollTo({top:0,behavior:'smooth'});}),button('Delete',async()=>{await api('memories/'+m.id+'/delete',{});await refresh();}));c.append(actions);return c;},'No saved memory yet. Agents save preferences, decisions and checkpoints here as they work.');
 if(activeTab!=='system')return;
 const o=await api('overview');
 const kv=$('connections');kv.replaceChildren();if(o.connections.error){kv.append(node('p',o.connections.error));}else for(const [k,v] of Object.entries(o.connections)){kv.append(node('div',(k==='claude'?'Claude Code':'Codex')+': '+(v.signed_in?'connected':'not connected')+(v.installed?'':' (not installed)')+' · '+v.used_today+'/'+v.daily_limit+' in the last 24 h'));}
 $('escalations').replaceChildren(...(o.escalations.length?o.escalations.map(e=>node('div',date(e.created_at)+' · '+(e.requested_by||'console')+' · '+e.detail,'event')):[node('p','None yet.','muted')]));
 const row=cells=>{const tr=node('tr');cells.forEach(v=>tr.append(node('td',String(v??''))));return tr;};
 $('people').tBodies[0].replaceChildren(...o.people.map(p=>row([p.who,p.tasks,p.active,p.completed,p.failed,p.model_calls,p.input_tokens.toLocaleString()+' / '+p.output_tokens.toLocaleString(),p.projects,date(p.last_task)])));
 $('projects-table').tBodies[0].replaceChildren(...o.projects.map(p=>row([p.name,p.tasks,p.active,p.memories,p.files])));
}
function skillDescription(){$('skill-description').textContent=state?.skills.find(s=>s.id===$('skill').value)?.description||'';}
async function showJob(id){const j=await api('jobs/'+id+'/timeline');$('detail-task').textContent=j.task;$('detail-status').textContent=j.status;$('detail-result').textContent=j.result||j.error||'The task has not produced a final answer yet.';$('detail-plan').replaceChildren(...j.plan.map(s=>node('li',s.status.replaceAll('_',' ')+' · '+s.title)));$('detail-actions').replaceChildren(button('Download handoff',async()=>{const result=await api('jobs/'+id+'/handoff',{});await download(result);await refresh();}));if(j.status==='completed')$('detail-actions').append(button('Mark reviewed',async()=>{await api('jobs/'+id+'/review',{});$('job-dialog').close();await refresh();}));$('detail-meta').textContent=[j.requested_by?'From '+j.requested_by:'From the console',j.skill,j.profile,j.model_calls+' model calls',j.started_at?'started '+date(j.started_at):'',j.finished_at?'finished '+date(j.finished_at):''].filter(Boolean).join(' · ');$('detail-files').replaceChildren(...j.artifacts.map(a=>button(a.name,()=>download(a))));$('detail-files-section').hidden=!j.artifacts.length;$('detail-workspace-section').hidden=!j.thread;if(j.thread){const w=await api('workspace/files?project='+encodeURIComponent(j.project)+'&thread='+encodeURIComponent(j.thread));$('detail-folder').textContent=w.folder+' · '+w.files.length+' files (shared by the whole chat)';$('detail-workspace').replaceChildren(...w.files.map(f=>{const r=node('div',undefined,'file-row');r.append(node('span',f.path),node('span',(f.bytes/1024).toFixed(1)+' KB','muted'),button('Download',()=>downloadPath('workspace/file?project='+encodeURIComponent(j.project)+'&thread='+encodeURIComponent(j.thread)+'&path='+encodeURIComponent(f.path),f.path.split('/').pop())));return r;}));}$('detail-events').replaceChildren(...j.events.map(e=>{const d=node('div',undefined,'event '+e.kind);d.append(node('span',new Date(e.created_at).toLocaleTimeString(),'muted'),node('span',e.kind,'kind'),node('span',e.detail));return d;}));if(!$('job-dialog').open)$('job-dialog').showModal();}
async function download(a){return downloadPath('artifacts/'+a.id,a.name);}
async function downloadPath(path,name){const a={name};const response=await fetch('/api/'+path,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw Error('Could not load this file.');const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download=a.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function form(id,action){$(id).addEventListener('submit',async e=>{e.preventDefault();notice();const submit=e.submitter;if(submit)submit.disabled=true;try{await action();}catch(error){notice(error.message);}finally{if(submit)submit.disabled=false;}});}
form('unlock-form',async()=>{token=$('owner-key').value.trim();try{await refresh();$('owner-key').value='';}catch(error){token='';throw error;}});
form('task-form',async()=>{await api('jobs',{project,task:$('task').value,skill:$('skill').value,profile:$('profile').value,allow_frontier:$('frontier').checked,allow_images:$('images').checked});$('task').value='';await refresh();if(!state.configured)notice('Task saved. Set HUB_URL and HUB_KEY in agents/.env, then restart the controller to begin.');});
form('project-form',async()=>{const result=await api('projects',{name:$('new-name').value,brief:$('new-brief').value});project=result.id;$('project-dialog').close();$('project-form').reset();await refresh();});
form('source-form',async()=>{await api('documents',{project,title:$('source-title').value,source:$('source-origin').value||'user supplied',text:$('source-text').value});$('source-form').reset();await refresh();notice('Source added to this project.');});
form('memory-form',async()=>{await api('memories',{project,title:$('memory-title').value,content:$('memory-content').value,kind:$('memory-kind').value});$('memory-form').reset();await refresh();notice('Memory saved.');});
$('source-file').addEventListener('change',async()=>{const f=$('source-file').files[0];if(!f)return;if(f.size>2_000_000){notice('Choose a text file smaller than 2 MB.');return;}$('source-text').value=await f.text();if(!$('source-title').value)$('source-title').value=f.name;if(!$('source-origin').value)$('source-origin').value=f.name;});
$('project').addEventListener('change',()=>{project=$('project').value;refresh().catch(e=>notice(e.message));});$('skill').addEventListener('change',skillDescription);$('refresh').addEventListener('click',()=>refresh().catch(e=>notice(e.message)));$('activity-refresh').addEventListener('click',()=>refresh().catch(e=>notice(e.message)));['activity-scope','memory-scope'].forEach(id=>$(id).addEventListener('change',()=>refresh().catch(e=>notice(e.message))));$('memory-search').addEventListener('input',()=>refresh().catch(e=>notice(e.message)));$('new-project').addEventListener('click',()=>{if(!token)return notice('Unlock the workspace first.');$('project-dialog').showModal();});$('lock').addEventListener('click',()=>{token='';state=undefined;rendered.clear();$('workspace').hidden=true;$('unlock').hidden=false;$('connection').textContent='Locked';notice();});document.querySelectorAll('.nav').forEach(e=>e.addEventListener('click',()=>{tab(e.dataset.tab);if(state)refresh().catch(x=>notice(x.message));}));document.querySelectorAll('[data-close]').forEach(e=>e.addEventListener('click',()=>$(e.dataset.close).close()));setInterval(()=>{if(state&&!document.hidden)refresh().catch(e=>notice(e.message));},6000);

// Signed in through Cloudflare Access as the owner: the controller recognises you and no key is needed.
tab('activity');refresh().catch(()=>{});
